- name: Disable IE11 as standalone browser
  hosts: windows
  gather_facts: no
  tasks:
    - name: Set NotifyDisableIEOptions
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\Main
        name: NotifyDisableIEOptions
        data: 2
        type: dword