---
- name: Install CrowdStrike Falcon Sensor
  hosts: all
  become: yes
  vars:
    falcon_sensor_package: "/tmp/falcon-sensor.rpm"  # Update this path for your package
    customer_id: "YOUR_CUSTOMER_ID"  # Replace with your actual CID

  tasks:
    - name: Determine OS family
      ansible.builtin.setup:
      register: system_info

    - name: Upload Falcon Sensor package
      ansible.builtin.copy:
        src: "{{ falcon_sensor_package }}"
        dest: "/tmp/falcon-sensor"
