---
- name: Uninstall Microsoft LAPS Agent
  hosts: windows
  gather_facts: yes
  tasks:
    - name: Uninstall LAPS using win_package
      win_package:
        product_id: "{F8C2AEE8-5F00-49E5-B6AB-7391E9830523}"  # Replace with actual LAPS Product ID
        state: absent
      register: laps_uninstall

    - name: Display uninstall results
      debug:
        msg: "LAPS uninstall result: {{ laps_uninstall }}"


v2

- name: Uninstall Legacy LAPS
  hosts: windows_servers
  gather_facts: yes
  tasks:
    
    - name: Uninstall LAPS using MSIEXEC
      ansible.windows.win_command: 
        cmd: 'msiexec /x {LAPS-PRODUCT-CODE} /qn /norestart'
      register: uninstall_laps
      ignore_errors: yes

    - name: Remove LAPS directory
      ansible.windows.win_file:
        path: "C:\\Program Files\\LAPS"
        state: absent

    - name: Remove LAPS PowerShell module
      ansible.windows.win_file:
        path: "C:\\Program Files\\LAPS\\AdmPwd.PS"
        state: absent

    - name: Delete LAPS Registry Keys
      ansible.windows.win_registry:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\LAPS
        state: absent

    - name: Remove LAPS Policies
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft Services\AdmPwd
        state: absent

    - name: Reboot if needed
      ansible.windows.win_reboot:
        when: uninstall_laps is changed
